language: objective-c
xcode_project: SkyFloatingLabelTextField/SkyFloatingLabelTextField.xcodeproj
xcode_scheme: SkyFloatingLabelTextField
script:
  - bundle exec rake ci
matrix:
  include:
    - osx_image: xcode10.2
      env: SWIFT=5.0 BUILD_SDK=iphonesimulator12.2 DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - osx_image: xcode10
      env: SWIFT=4.2 BUILD_SDK=iphonesimulator12.0 DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - osx_image: xcode9.2
      env: SWIFT=4.0 BUILD_SDK=iphonesimulator11.2 DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - osx_image: xcode9.4
      env: SWIFT=4.1 BUILD_SDK=iphonesimulator11.4 DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - osx_image: xcode9.4
      env: SWIFT=3.3 BUILD_SDK=iphonesimulator11.4 DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - osx_image: xcode8.3
      env: SWIFT=3.1 BUILD_SDK=iphonesimulator10.3 DESTINATION="platform=iOS Simulator,name=iPhone 7"

