language: objective-c

branches:
  only:
   - master

xcode_project: SkyFloatingLabelTextField/SkyFloatingLabelTextField.xcodeproj
xcode_scheme: SkyFloatingLabelTextField
osx_image: xcode9
xcode_sdk: iphonesimulator11.2
script:
  - bundle exec rake ci

